import Head from 'next/head'
import Image from 'next/image'
import Content from '../components/Content'
import styles from '../styles/Home.module.css'
import { ClerkProvider, useUser, SignIn, UserButton, SignedOut } from '@clerk/nextjs'

export default function Home() {
  const { isLoaded, isSignedIn, user } = useUser()
  console.log(user)
  return (
    <Content className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <SignIn />
        <UserButton />

      </main>
    </Content>
  )
}
